# Generated by Django 6.1.1 on 2026-10-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapsuleDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_query', models.CharField(max_length=150)),
                ('album_title', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('release_year', models.CharField(blank=True, max_length=10)),
                ('ai_review', models.TextField()),
                ('youtube_search_term', models.CharField(max_length=300)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
