# Generated by Django 6.1.1 on 2026-10-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
